# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
kotlin.code.style=official
android.useAndroidX=true
android.enableJetifier=true

# Force Gradle to use the JDK bundled with Android Studio
# Note: Backslashes and Colons must be escaped in .properties files
org.gradle.java.home=C\:\\Program Files\\Android\\Android Studio\\jbr

# Performance and Memory optimizations
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Force Kotlin to compile inside the Gradle daemon to save memory
kotlin.compiler.execution.strategy=in-process
